### ISSUE TITLE
hashbang meta

### ISSUE THREAD

**Issue by A** [visionmedia/page.js#229]
Probably, `hashbang` isn't best feature for now. 
- [ ] #222 looks like it's related to `hashbang` too
- [ ] #228 problems with `base`
- [ ] #209 problem with protocol 
- [ ] #204 docs
- [ ] #242 Going to root url when hashbang is true, and you have something in location.pathname, duplicates pathname

**Comment by shuvalov-anton** [comment]
Hashbang navigation is a super buggy feature of the pagejs and, IMHO this feature isn't required by most of the users. I can move the hashbang from core into the separate plugin. This change should simplify the core. I need some time to make the idea out. All opinions and comments are welcomed // cc @kethinov @rstacruz

**Comment by rstacruz** [comment]
:+1: on removing hashbang.

**Comment by danielhickman** [comment]
+1 and /sub
